### ISSUE TITLE
Some unused art

### ISSUE THREAD

**Issue by BBoldt** [RCXcrafter/MoreChisels#4]
Hey, I was the texture artist for the original MoreChisels, I didn't know about this fork.

Here are some textures I made ages ago that may or may not have been used:

[AllChisels.zip](https://github.com/RCXcrafter/MoreChisels/files/416764/AllChisels.zip)

**Comment by RCXcrafter** [comment]
![chisel_chisel](https://cloud.githubusercontent.com/assets/10962454/17650684/d5904ea8-6253-11e6-9fbf-9eae84f5e608.png)
Literally what.

So I guess I'll add some tropicraft chisels. Thanks.
